### ISSUE TITLE
Analysis report part 1 feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [aburaksahin/intergalactica#2]
Overall, you guys did a great job in describing the exact functionality required by the game. There are some major problems in the UC descriptions though since you constantly refer to the UI, where UI design is not performed yet. See comments in attached document.
[18.analysis.1.pdf](https://github.com/aburaksahin/intergalacticaGr18/files/538340/18.analysis.1.pdf)

**Comment by aburaksahin** [comment]
Done!
